### ISSUE TITLE
Import warning when opening „SecureTokenAuthBypass“ profile

### ISSUE THREAD

**Issue by vasquesbc** [erikberglund/ProfileCreator#81]
I got this warning:

> Payload Keys currently unavailable in ProfileCreator:
> 
> • com.apple.MCX
>   - cachedaccounts.askForSecureTokenAuthBypass

when trying to open the profile described here: [https://soundmacguy.wordpress.com/2018/06/02/bypassing-the-securetoken-dialog-for-mobile-accounts/](url)

**Comment by erikberglund** [comment]
Thanks, yes that key is currently not added to the manifest in ProfileCreator. I will add it and let you know when its ready to be downloaded as a payload update

**Comment by erikberglund** [comment]
There is a slight issue with this payload though, and it will require a code change unfortunately as the com.apple.MCX is a grab bag of very different settings that still should be considered their own payload, but the app doesn't allow for multiple payloads with the same PayloadType. That is planned to be fixed so I will have to add that fix to the next app update to get this in. I have added it to my list.

**Comment by vasquesbc** [comment]
thanks for your effort.
take your time.

**Comment by erikberglund** [comment]
This will finally be solved with the next release.

**Comment by vasquesbc** [comment]
I've tested it with the current release and still getting the same message

**Comment by vasquesbc** [comment]
OK - i've found the right template inside of ProfileCreator and it works!
